server:
    port: 7070
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
        defaultZone: http://localhost:1000/eureka/
spring: 
  application:
    name: SpringCloud-UserService-ConfigClient 
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java1909?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    
  zipkin:
    enabled: true
    base-url: http://localhost:9411