server:
    port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
        defaultZone: http://localhost:1000/eureka/
spring: 
  application:
    name: SpringCloud-FeignService-ConfigClient     
  thymeleaf:
    prefix:  classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  zipkin:
    enabled: true
    base-url: http://localhost:9411    
feign:
  hystrix:
    enabled: true